### ISSUE TITLE
I can't login after confirm email in the Authentication example

### ISSUE THREAD

**Issue by dytra** [jlengstorf/dynamic-jamstack-examples#1]
I've just signed up using my email , received the confirmation email
then after I clicked the link and then try to login
it says that my email hasn't confirmed

**Comment by jlengstorf** [comment]
@dytra are you using the example site from the article, or your own fork/deployment?

if it's your deployment: are you using the Netlify-deployed site for signup/confirmation? or the localhost site? Email confirmation requires the site to be deployed.

If you're testing and don't care about confirming emails, you can also turn off email verification in the Netlify UI under the Identity settings.

<img width="700" alt="Screen Shot 2019-12-20 at 10 58 00 AM" src="https://user-images.githubusercontent.com/163561/71284544-d1d77600-2317-11ea-9e4a-a4251dd04299.png">

if you're using the example site, did you see any errors? what did you see when you clicked the confirmation email? let's try to get this figured out together!

thanks for reading!

**Comment by dytra** [comment]
I'm using the example site

After I clicked the **confirm my email address** link on the email

It redirects me to https://dynamic-jamstack-examples.netlify.com/#confirmation_token=randomtoken

the view is the homepage of the dynamic jamstack examples

I clicked the Authentication link then tried to login with the same email

But still it gave me the error "Email not confirmed" on the netlify login form

It seems my email isn't confirmed after I click the in email confirm link

**Comment by jlengstorf** [comment]
thanks so much for adding extra detail, @dytra! I figured out what went wrong: I hadn't included the Netlify Identity widget script on the home page, so the confirmation wasn't working 😱 

I've fixed it now (see https://github.com/jlengstorf/dynamic-jamstack-examples/commit/97e197146bac8716230a2b84b4e43851bc6f7390) and just verified it working

thanks again for reading and filing this issue!

**Comment by dytra** [comment]
nice, it's working now
Your welcome
